[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run db:push --workspace=packages/db && npm run start --workspace=apps/web"
healthcheckPath = "/"
healthcheckTimeout = 100
