[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
preDeployCommand = "npx prisma db push --accept-data-loss --schema=packages/db/prisma/schema.prisma"
startCommand = "npm run start --workspace=apps/web"
healthcheckPath = "/"
healthcheckTimeout = 100
