DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'JournalType') THEN
    CREATE TYPE "JournalType" AS ENUM ('INTERNATIONAL', 'LOCAL');
  END IF;
END $$;

ALTER TABLE "Journal"
  ADD COLUMN IF NOT EXISTS "type" "JournalType" NOT NULL DEFAULT 'INTERNATIONAL',
  ADD COLUMN IF NOT EXISTS "localRank" TEXT,
  ADD COLUMN IF NOT EXISTS "issuesPerYear" INTEGER;
